.changeset/happy-spies-hide.md, packages/design-system/src/atoms/toast/index.tsx, packages/design-system/src/atoms/toast/toast.stories.tsx
1. Added `warn` variant to `Toast`.
2. Added `duration` prop to `Toast.show`.
=> add warn variant & duration prop to toast

.changeset/good-camels-end.md, packages/design-system/README.md, packages/design-system/package.json, packages/design-system/rollup.config.js
Web, native, android & ios builds are divided now.
=> Divide web, native, android & ios builds

.changeset/smart-snakes-begin.md, packages/cli/README.md, packages/cli/format.js, packages/cli/get-all-files.js, packages/cli/get-changed-files.js, packages/cli/lint.js, packages/eslint-config/README.md, packages/eslint-config/package.json, packages/prettier-config/README.md
1. Use only `js,ts,jsx,tsx` for formatting.
2. Make linter to require peer deps.
=> Update linter & formatter

.changeset/quiet-snakes-swim.md, packages/design-system/.storybook/utils.ts, packages/eslint-config/package.json, yarn.lock
Removed react & ts from eslint config peer deps list.
=> Remove useless peer deps

.changeset/nice-insects-count.md, packages/eslint-config/package.json
1. Added `eslint-plugin-jest` to the peer deps list.
=> Add jest plugin to peer deps

.changeset/sharp-socks-draw.md, packages/eslint-config/.eslintrc.js
Added `jest` globals to the eslint config.
=> Add jest globals to eslint config

.changeset/friendly-geckos-bow.md, packages/design-system/src/molecules/accountDropdown/index.tsx, packages/design-system/src/molecules/connectWeb3Button/connectWeb3Button.stories.tsx, packages/design-system/src/molecules/connectWeb3Button/index.tsx
- Made `ConnectWeb3Button` cross-platform by removing class names.
1. Run `yarn start` & go to `ConnectWeb3Button` story.
=> Make ConnectWeb3Button cross-platform

.changeset/early-eyes-impress.md, packages/feature-flag/src/index.test.tsx, packages/feature-flag/src/index.tsx
Added a high-order component to consume feature flags.
Run `yarn test`
=> Add feature flags high-order component

.changeset/famous-sloths-sell.md, packages/design-system/src/molecules/footer/index.tsx, packages/design-system/src/styles/margin.ts, packages/design-system/src/styles/padding.ts
Removed classNames from Footer. Replaced with the common style definitions.
1. Run `yarn start` inside `design-system` package.
=> make Footer component style-agnostic

.changeset/angry-avocados-teach.md, packages/design-system/__mocks__/fileMock.js, packages/design-system/__mocks__/svgMock.js, packages/design-system/ios/Podfile.lock, packages/design-system/jest.config.js, packages/design-system/package.json, packages/design-system/src/atoms/popover/index.native.tsx, packages/design-system/src/atoms/tooltip/index.native.tsx, packages/design-system/src/hooks/native.ts, packages/design-system/src/molecules/dropdown/index.tsx, packages/design-system/src/molecules/select/index.tsx, packages/design-system/src/molecules/select/select.test.tsx, packages/design-system/src/providers/tryroll/index.tsx, packages/design-system/src/utils/formatters.ts, yarn.lock
- Improve select rendering performance
- Add unit tests to the design system via the fastest `swc` compiler.
1. Run a storybook for all the environments.
2. Run `yarn test`.
=> Improve select rendering performance

.changeset/silly-ties-think.md, packages/feature-flag/src/index.tsx
- Added `useFeatureFlagsLoading` hook to expose loading state.
=> add feature flags loading hook

packages/feature-flag/src/index.tsx
- Fixed typings for `allSettled` function.
=> Fix all settled types

.changeset/dry-lions-grin.md, packages/api/package.json, packages/api/src/auth/index.test.ts, packages/api/src/auth/index.ts, packages/api/src/client/index.test.ts, packages/api/src/client/index.ts, packages/api/src/index.ts, packages/api/src/utils/get-random-string.ts, packages/api/src/utils/index.ts, packages/api/src/utils/pick-query-string-item-from-url.ts, packages/sdk/src/auth/index.test.ts, packages/sdk/src/auth/index.ts, yarn.lock
- Added API Client.
`yarn test`
=> Add API client

.changeset/strange-ravens-develop.md, packages/api/src/client/index.test.ts, packages/api/src/client/index.ts
Added authorization handler for API client.
`yarn test`
=> Add authorization handler

.github/workflows/release.yml, yarn.lock
1. Updated lock file.
2. Use frozen lock file option for release.
=> Update lock file

.changeset/pink-adults-think.md, packages/api/src/client/index.test.ts, packages/api/src/client/index.ts, packages/sdk/src/auth/index.ts
- Used arrow functions to avoid `bind` in SDK.
- Updated error handling in the API (reject on error response code).
`yarn test`
=> Update error handling

.changeset/warm-keys-work.md, packages/api/src/client/index.ts
- Make API client to accept async handlers
- `yarn test`
=> Make API client to accept async handlers

.github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/version-packages.yml, README.md, yarn.lock
- Made lockfile updates automatic on the Version Packages PR.
=> Update lockfile automatically

.changeset/silent-paws-smoke.md, packages/api/src/client/index.test.ts, packages/api/src/client/index.ts, packages/sdk/src/auth/index.test.ts, packages/sdk/src/auth/utils.ts
- Fixed token expiration check.
=> Fix expiration check

.changeset/orange-ravens-join.md, packages/api/src/client/index.ts
=> Update call method typing

.changeset/hot-peaches-rhyme.md, packages/api/package.json, packages/cli/package.json, packages/contract-bindings/package.json, packages/design-system/package.json, packages/eslint-config/package.json, packages/feature-flag/package.json, packages/prettier-config/package.json, packages/sdk/package.json, packages/sdk/src/auth/index.test.ts
- Updated engines to match any 16 Node.
=> Update node version

.changeset/moody-rocks-check.md, packages/design-system/src/molecules/invalidNetworkBanner/index.tsx, packages/design-system/src/molecules/invalidNetworkBanner/invalidNetworkBanner.stories.tsx
Remove action on invalid network banner.
=> feat: Remove action on invalid network banner

.changeset/polite-mugs-destroy.md, packages/sdk/src/auth/index.test.ts, packages/sdk/src/auth/utils.ts
- Fixed refresh condition.
1. `yarn test`
=> Fix refresh condition

.changeset/khaki-starfishes-pay.md, packages/design-system/src/utils/web3.test.tsx, packages/design-system/src/utils/web3.ts, packages/design-system/src/web3/connectors.tsx
- Added util function to get etherscan link based on chain ID.
- Export Polygon network chain ID.
=> feat: get etherscan link

.changeset/mighty-bugs-hang.md, packages/api/src/index.ts, packages/api/src/transaction/index.ts, packages/api/src/transaction/transaction.ts, packages/api/src/transaction/types.ts, packages/api/src/user/index.ts, packages/api/src/user/types.ts, packages/api/src/user/user.ts
- Added transaction & user APIs needed for https://github.com/TuringAdvisoryGroup/oauth-client-example/.
Ensure the endpoints & methods are correct.
=> Add transaction & user APIs

.changeset/blue-turkeys-deny.md, packages/design-system/package.json, packages/design-system/src/hooks/web3.ts, packages/design-system/src/providers/web3/index.tsx, packages/design-system/src/providers/web3Connectors/index.tsx, yarn.lock
- Replace `web3-react-core` in favor of `@web3-react/core`
`yarn test`
=> Replace web3-react-core in favor of @web3-react/core

.changeset/stale-lamps-tease.md, packages/sdk/src/auth/sdk.test.ts, packages/sdk/src/auth/sdk.ts, packages/sdk/src/auth/types.ts
-Added missing redirect url to auth sdk getLogOutUrl
`yarn test`
=> Add missing redirect url to auth sdk getLogOutUrl

.changeset/spotty-yaks-turn.md, packages/sdk/src/auth/api.ts
- Pass form urlencoded data to refresh tokens request
=> Pass form urlencoded data to refresh tokens request

.changeset/rich-geese-sing.md, packages/api/src/index.ts, packages/api/src/token/index.ts, packages/api/src/token/token.ts, packages/api/src/token/types.ts, packages/api/src/transaction/transaction.ts, packages/api/src/transaction/types.ts, packages/api/src/user/types.ts, packages/api/src/user/user.ts
Add new endpoints using [this docs](https://github.com/TuringAdvisoryGroup/documentation/blob/master/api-design/api-design-document.md) as a reference for:
- User
- Transaction
- Token
#200
=> feat: Add token, user and transaction endpoints

.changeset/calm-carrots-vanish.md, packages/design-system/src/atoms/input/index.tsx
- Fixed issue when label overflows input value.
=> Fix input label overflow

.changeset/flat-frogs-listen.md, packages/sdk/src/auth/api.ts
- Add auth prop on axios options for requestClientToken method.
=> fix: requestClientToken method

.changeset/healthy-brooms-perform.md, packages/design-system/package.json, yarn.lock
- Added missing `@wagmi/core` lib.
=> Add missing wagmi core lib

.changeset/config.json, .changeset/eleven-dryers-drop.md, examples/example-node-api-client/.env.example, examples/example-node-api-client/generate-api-client.ts, examples/example-node-api-client/index.ts, examples/example-node-api-client/package.json, examples/example-node-api-client/tokens.ts, examples/example-node-api-client/tsconfig.json, examples/example-node-api-client/users.ts, packages/api-client/src/client.ts, packages/api/src/token/token.ts, packages/api/src/token/types.ts, packages/api/src/user/types.ts, packages/api/src/user/user.ts, packages/sdk/src/auth/api.ts, packages/sdk/src/auth/types.ts, yarn.lock
- Created a node cli for using api as a client
- Fixed some types on api package
- Added get user token balance endpoint on api
- Added scope property when requesting a client token
- Create enum with possible scope options
https://www.loom.com/share/fb6d9433bdce4fc08d4640ba9b184cc8
=> feat: Add example node api client

examples/example-node-api-client/users.ts
Handle empty balances on node api client
1- Run the the example-node-api-client
2- Check user balances option
3- Check a user that does not have any balance on its account
4- This message should show up `User has no balances`
=> feat: Handle empty balances on node api client

.changeset/sharp-geckos-sing.md, packages/design-system/src/molecules/analyticsCard/index.tsx, packages/design-system/src/molecules/featureCard/index.tsx, packages/design-system/src/molecules/tokenCard/index.tsx
=> Add style prop to cards

.changeset/rare-lizards-roll.md, packages/design-system/src/atoms/buttonV2/index.tsx, packages/design-system/src/atoms/buttonV2/types.ts
=> Add style prop to button

.changeset/silver-ducks-sleep.md, packages/design-system/package.json, packages/design-system/src/atoms/popover/index.native.tsx, packages/design-system/src/atoms/popover/index.web.tsx, packages/design-system/src/atoms/tooltip/index.native.tsx, packages/design-system/src/atoms/tooltip/index.web.tsx, packages/design-system/src/molecules/select/index.tsx, yarn.lock
=> Update floating ui lib

.changeset/chatty-donkeys-add.md, packages/design-system/src/atoms/popover/index.web.tsx
- Allowed popover to open on click.
=> Allow popover to open on click

.changeset/happy-lamps-walk.md, examples/example-node-api-client/tokens.ts, packages/api/src/token/token.ts, packages/api/src/transaction/transaction.ts, packages/api/src/transaction/types.ts, packages/api/src/user/user.ts
- Update API endpoints version
- Removed empty query string params from URL on `getTokens`
=> Update api endpoints

.gitignore, examples/example-node-api-client/generate-api-client.ts, packages/sdk/README.md
Updating documentation for the sdk.
=> quickstart

.changeset/clever-buckets-wonder.md, .changeset/strong-balloons-agree.md, packages/design-system/src/molecules/rightSidebar/index.tsx, packages/sdk/src/auth/sdk.ts
- Added right sidebar spacer.
- Clear SDK when not enough data to refresh.
=> Add right siderbar spacer

.changeset/angry-boxes-remember.md, packages/design-system/src/molecules/rightSidebar/index.tsx, packages/design-system/src/molecules/sidebar/desktop.tsx
- Extracted right sidebar spacer out of the fixed parent.
=> Extract right sidebar spacer out of fixed parent

.changeset/chatty-knives-tell.md, .changeset/clean-donuts-bake.md, .changeset/fair-pumas-laugh.md, examples/example-node-api-client/users.ts, examples/example-web-oauth-client/src/config.ts, packages/api-client/package.json, packages/api/src/user/user.ts, packages/design-system/src/molecules/rightSidebar/index.tsx, packages/design-system/src/molecules/sidebar/desktop.tsx, packages/session-manager/src/native-session-provider.tsx, packages/session-manager/src/session-provider.test.tsx, packages/session-manager/src/session-provider.tsx, packages/session-manager/src/types.ts, scripts/build-dependents-graph.js, yarn.lock
- Fixed layout's sidebars are not clickable
- Updated `getMe` to the latest version
=> Fix layout & update getMe

.changeset/flat-zoos-shake.md, packages/api/package.json, yarn.lock
=> Update api client

.changeset/forty-cows-shout.md, packages/api-client/src/client.ts
- Remove unauthorized event fire on queue destroy
=> Remove unauthorized event fire on queue destroy

.changeset/breezy-ladybugs-prove.md, packages/design-system/src/organisms/avatarPicker/avatarPicker.native.tsx, packages/design-system/src/organisms/avatarPicker/avatarPicker.stories.tsx, packages/design-system/src/organisms/avatarPicker/avatarPicker.web.tsx, packages/design-system/src/organisms/avatarPicker/types.ts
- Added value prop to AvatarPicker.
=> Add value prop to AvatarPicker

.changeset/brown-peas-dance.md, packages/design-system/src/atoms/buttonV2/index.tsx, packages/design-system/src/atoms/typographyV2/index.tsx, packages/design-system/src/molecules/footerV2/index.tsx, packages/design-system/src/molecules/header/index.tsx, packages/design-system/src/molecules/inputLayout/index.tsx, packages/design-system/src/molecules/inputLayout/inputLayout.stories.tsx, packages/design-system/src/organisms/formStepHeader/index.tsx
- Use percentage on InputLayout component
- Change responsive breakpoint
#277 
#269
=> fix: i269 change responsive breakpoint

examples/example-node-api-client/users.ts, examples/example-node-api-client/utils.ts, packages/api/src/user/types.ts, packages/api/src/user/user.ts, packages/auth-client-credentials-sdk/src/api.ts, packages/auth-node-sdk/src/types.ts
=> chore: consistent platform user endpoint definition

examples/example-node-api-client/users.ts, examples/example-node-api-client/utils.ts, packages/auth-node-sdk/src/api.ts, packages/auth-node-sdk/src/utils.ts
=> fix: explicitly use https package

.changeset/violet-jeans-double.md, examples/example-node-api-client/index.ts, examples/example-node-api-client/transaction.ts, examples/example-node-api-client/users.ts, packages/api/src/user/types.ts, packages/api/src/user/user.ts
supporting new platform user apis to get balances and address
=> Platform user balances

examples/example-node-api-client/transaction.ts
- Fixed old imports in the example node API client.
- Resolved merge conflict.
=> Fix old imports

.changeset/violet-jeans-double.md
- repairing changeset name based on new `roll-network` packages
=> fix: update changeset package name

.changeset/dry-tools-wonder.md, examples/example-node-api-client/transaction.ts, packages/api/src/transaction/transaction.ts, packages/api/src/transaction/types.ts
- Add correct types for transaction response
- Format correctly response on example project
- Fixed prompt in request body
=> chore: api send transaction

.changeset/ninety-timers-exist.md, .changeset/warm-waves-relate.md, examples/example-node-api-client/README.md, examples/example-node-api-client/index.ts, examples/example-node-api-client/transaction.ts, packages/api/src/transaction/transaction.ts, packages/api/src/transaction/types.ts
- Created a definition for a batchSend in `packages/api/transaction.ts`
- Provided an example in sendBatchFromPlatformUser in `example-node-api-client/ transaction.ts `
- Update Choice enum and ActionByChoice in index.ts with Send Batch For Platform User option
- Add README.md with documentation for `example-node-api client`
sendBatchFromPlatformUser has to be verified in the command line prompt
=> feat: new branch with a batchSend example

.changeset/large-pumas-brake.md, packages/api-client/src/client.test.ts, packages/api-client/src/request-manager.ts, packages/auth-sdk/src/code-token-interaction/code-token-interaction.ts
=> Fix refresh token flow

.changeset/breezy-seas-teach.md, packages/auth-sdk/src/sdk.ts, packages/auth-sdk/src/store/in-memory-store.ts, packages/auth-sdk/src/store/key-value-store-adapter.ts, packages/auth-sdk/src/store/types.ts
=> Fix store count

.changeset/friendly-rules-search.md, packages/api/src/transaction/transaction.ts
- Update response batch send response type to match [backend changes](https://github.com/roll-network/roll-go/pull/3872)
=> chore: update response type batch send

.changeset/wise-dryers-count.md, packages/design-system/jest.config.native.js, packages/design-system/jest.config.web.js, packages/design-system/package.json, packages/design-system/setupJest.native.js, packages/design-system/setupJest.web.js, packages/design-system/src/hooks/web3Wagmi.tsx, packages/design-system/src/organisms/uniswapWidget/index.web.tsx, packages/design-system/src/providers/web3ProviderWagmi/index.tsx, packages/design-system/src/providers/web3ProviderWagmi/utils.ts, packages/design-system/src/utils/web3.ts, packages/design-system/src/web3/connectors.tsx, packages/design-system/src/window.d.ts, yarn.lock
- removed all reference of etherjs
- add viem as a replacement of etherjs
#293
=> chore: Update wagmi and web3modal

.changeset/shaggy-pots-pretend.md, packages/contract-bindings/src/withdrawal/abi/Withdrawal.json, packages/contract-bindings/src/withdrawal/contracts/Withdrawal.ts, packages/contract-bindings/src/withdrawal/contracts/factories/Withdrawal__factory.ts
Withdrawal contract bindings updated.
=> chore: update withdrawal contract bindings

.changeset/poor-items-lick.md, packages/design-system/src/molecules/header/header.stories.tsx, packages/design-system/src/molecules/header/index.tsx, packages/design-system/src/molecules/header/types.ts, packages/design-system/src/molecules/sidebar/mobile.tsx
Update HeaderV2 component to support top element on mobile sidebar
=> chore: Update HeaderV2 component to support top element on mobile sidebar

.changeset/tasty-moles-leave.md, packages/design-system/src/atoms/inputV2SelectSuffix/index.tsx, packages/design-system/src/atoms/popover/index.d.ts, packages/design-system/src/atoms/popover/index.web.tsx, packages/design-system/src/atoms/tooltip/index.web.tsx, packages/design-system/src/molecules/inputV2/index.tsx, packages/design-system/src/molecules/select/index.tsx, packages/design-system/src/molecules/selectV2/index.tsx, packages/design-system/src/molecules/selectV2/selectV2.test.tsx
- Fixed select options are not pressable in app
Closes #388
=> Fix select options are not pressable in app

.changeset/tall-lobsters-flow.md, packages/session-manager/src/hooks/use-auth-sdk-user.test.ts, packages/session-manager/src/hooks/use-auth-sdk-user.ts, packages/session-manager/src/index.tsx, packages/session-manager/src/native-session-provider.tsx, packages/session-manager/src/session-provider.tsx, packages/session-manager/src/types.ts, packages/session-manager/src/utils/get-session-status.ts, packages/session-manager/src/utils/index.ts
- Made session status to be synced with user
=> Make session status to be synced with user

.changeset/large-drinks-hide.md, packages/design-system/src/molecules/alertV2/index.tsx
=> fix: remove margin on AlertV2 component

.changeset/new-cows-smoke.md, packages/design-system/.ondevice/storybook.requires.js, packages/design-system/ios/Podfile.lock, packages/design-system/src/molecules/select/index.tsx, packages/design-system/src/molecules/selectV2/index.tsx, packages/design-system/src/molecules/selectV2/selectV2.stories.tsx, packages/design-system/src/molecules/selectV2/selectV2.test.tsx
- Added search functionality to SelectV2.
=> Make SelectV2 searchable

.changeset/five-jokes-share.md, packages/design-system/src/molecules/alertV2/index.tsx
- Remove unnecessary paddings and margins on AlertV2 Component
#412
=> fix: AlertV2 layout

.changeset/olive-masks-lick.md, packages/api/package.json, yarn.lock
- Updated `api-client` package version in `api`
=> Update api client dependency

.changeset/sharp-cougars-appear.md, packages/design-system/src/molecules/sidebar/desktop.tsx
- Fixed zIndex of the spacer in the sidebar.
=> Fix sidebar is not clickable

.changeset/stale-pandas-raise.md, packages/design-system/src/molecules/select/index.tsx, packages/design-system/src/molecules/selectV2/index.tsx, packages/design-system/src/molecules/selectV2/selectV2.stories.tsx
- Added `loading` & `onSearchChange` to SelectV2
=> Add loading & onSearchChange to SelectV2

.changeset/config.json, examples/example-node-api-client/package.json, packages/api-client/package.json, packages/api/CHANGELOG.md, packages/api/package.json, packages/auth-sdk/package.json, packages/cli/package.json, packages/contract-bindings/package.json, packages/design-system/CHANGELOG.md, packages/design-system/package.json, packages/eslint-config/package.json, packages/feature-flag/package.json, packages/logger/package.json, packages/prettier-config/package.json, packages/session-manager/CHANGELOG.md, packages/session-manager/package.json
=> Rename org name

.changeset/shiny-lizards-tell.md, packages/api-client/package.json, packages/api/package.json, packages/auth-sdk/package.json, packages/cli/package.json, packages/contract-bindings/package.json, packages/design-system/package.json, packages/eslint-config/package.json, packages/feature-flag/package.json, packages/logger/package.json, packages/prettier-config/package.json, packages/session-manager/package.json
- update engine node versions
#427
=> chore: update engine node versions

.changeset/poor-ads-poke.md, packages/logger/src/logger.test.ts, packages/logger/src/logger.ts, packages/logger/src/types.ts
=> Clean up log entries

.changeset/great-tools-juggle.md, package.json, packages/api/src/transaction/types.ts, yarn.lock
Updated the type definitions in `SendArgs` with the parameters of  `platformType` and `platformID`
=> fix: update type definitions in transaction - SendArgs

.changeset/cold-monkeys-rescue.md, packages/design-system/src/molecules/tokenSelectContentV2/index.tsx, packages/design-system/src/organisms/tokenSelectV2/tokenSelectV2.stories.tsx, packages/design-system/src/organisms/tokenSelectV2/tokenSelectV2.test.tsx
- Add debounced for symbol and contract search
- Deprecate previous onSearch prop
#438
=> feat: Add support to search by symbol on TokenSelectV2

.changeset/chilly-paws-rush.md, packages/design-system/.storybook/preview.js, packages/design-system/src/providers/tryroll/index.tsx
- Added safeare provider to tryroll provider.
=> Add safearea provider to tryroll provider

examples/example-node-api-client/balances.ts, examples/example-node-api-client/client-credentials-token.ts, examples/example-node-api-client/client-credentials.ts, examples/example-node-api-client/index.ts, examples/example-node-api-client/tokens.ts, examples/example-node-api-client/transaction.ts, examples/example-node-api-client/users.ts
- Log the full error object
- Fix response log on loginMultiplePlatformUsers
- Log when there are no results on tokens endpoint
1- Run example-node-api-client
=> fix: Logs on example-node-api-client

.changeset/violet-kids-deny.md, packages/design-system/src/molecules/header/index.tsx, packages/design-system/src/organisms/layout/index.tsx
=> fix: height on mobile for layout and header components

.changeset/unlucky-scissors-breathe.md, packages/design-system/src/molecules/tokenSelectContentV2/index.tsx, packages/design-system/src/organisms/modal/index.web.tsx, packages/design-system/src/organisms/tokenSelectV2/tokenSelectV2.stories.tsx
- Add max height on TokenSelectV2
- Add max width on TokenSelectV2
- Use portal on Modal to prevent other elements to show on top of it
- Center elements horizontally on Modal
- Use lg size for Modal on mobile
#464
=> fix: TokenSelectV2 and Modal

.changeset/eighty-phones-melt.md, packages/api-client/src/request-manager.ts, packages/api-client/src/types.ts, packages/api-client/src/utils.ts
- Made redact error configurable
=> Make redact error configurable

examples/example-node-api-client/balances.ts, examples/example-node-api-client/client-credentials.ts, examples/example-node-api-client/tokens.ts, examples/example-node-api-client/users.ts, examples/example-node-api-client/utils.ts
https://github.com/roll-network/roll-go/issues/3986
=> fix: logger on example-node-api-client

.changeset/orange-comics-act.md, packages/design-system/ios/Podfile.lock, packages/design-system/metro.config.js, packages/design-system/src/molecules/inputContainer/index.tsx, packages/design-system/src/molecules/selectFilters/selectFilters.tsx, packages/design-system/src/organisms/table/table-filter.tsx, packages/design-system/src/organisms/table/table.native.tsx, packages/design-system/src/organisms/table/table.stories.tsx, packages/design-system/src/organisms/table/table.web.tsx, packages/design-system/src/organisms/table/types.ts
- Made Table filters responsive.
=> Make table filters responsive

.changeset/spotty-steaks-smoke.md, packages/design-system/src/atoms/buttonV2/index.tsx, packages/design-system/src/atoms/qrcode/index.tsx, packages/design-system/src/atoms/statusV2/index.tsx, packages/design-system/src/atoms/switch/index.tsx, packages/design-system/src/molecules/accountInfoDropdown/index.tsx, packages/design-system/src/molecules/alertV2/index.tsx, packages/design-system/src/molecules/analyticsCard/index.tsx, packages/design-system/src/molecules/featureCard/index.tsx, packages/design-system/src/molecules/footerV2/index.tsx, packages/design-system/src/molecules/inputLayout/index.tsx, packages/design-system/src/molecules/inputV2/index.tsx, packages/design-system/src/molecules/joinBanner/index.tsx, packages/design-system/src/molecules/rightSidebar/index.tsx, packages/design-system/src/molecules/selectV2/index.tsx, packages/design-system/src/molecules/sidebar/desktop.tsx, packages/design-system/src/molecules/sidebar/mobile.tsx, packages/design-system/src/molecules/sidebarOption/index.tsx, packages/design-system/src/molecules/sidebarOptions/index.tsx, packages/design-system/src/molecules/tokenCard/index.tsx, packages/design-system/src/molecules/walletCard/index.tsx, packages/design-system/src/organisms/avatarPicker/avatarPicker.native.tsx, packages/design-system/src/organisms/avatarPicker/avatarPicker.web.tsx, packages/design-system/src/organisms/formStepHeader/index.tsx, packages/design-system/src/organisms/layout/index.tsx, packages/design-system/src/organisms/table/table.native.tsx, packages/design-system/src/styles/text.ts, packages/design-system/src/styles/utils.ts, packages/eslint-config/.eslintrc.js
=> Unify style creation

.changeset/proud-dryers-dance.md, packages/design-system/src/molecules/selectFilters/selectFilters.tsx, packages/design-system/src/organisms/table/table.stories.tsx, packages/design-system/src/organisms/table/table.web.tsx, packages/design-system/src/styles/container.ts
- Added another select filter to `table.stories.tsx`
- Added a new media query in `SelectFilters` to check for the large devices and set `flexDirection: column `
=> feat: add media queries to make select filters responsive on large devices

.changeset/nine-trainers-relate.md, packages/design-system/src/molecules/sidebar/desktop.tsx
=> fix: handle footer component on sidebar

.changeset/shaggy-numbers-behave.md, packages/web3/src/connectors/connectors.tsx
=> chore: export form testnet chain id

.changeset/rotten-shirts-fold.md, packages/web3/src/providers/web3ProviderWagmi/chains.ts, packages/web3/src/providers/web3ProviderWagmi/utils.ts
=> feat: add form testnet on supported chains by wagmi

.changeset/tender-sheep-drop.md, packages/web3/src/connectors/connectors.tsx, packages/web3/src/utils/utils.ts
=> chore: update form testnet chain id and explorer url

.changeset/calm-bobcats-hide.md, packages/web3/src/connectors/connectors.tsx, packages/web3/src/providers/web3ProviderWagmi/chains.ts, packages/web3/src/utils/utils.ts
=> chore: Change form testnet values back to Caldera provider

.github/workflows/release.yml
- Changed version of the changeset action used.
=> chore: change changeset action version

.changeset/sharp-toes-live.md, packages/web3/src/providers/web3ProviderWagmi/utils.ts
=> fix: properly map sepolia
