roll-network/tryrolljs

- .changeset/giant-jobs-nail.md
- package.json
- packages/feature-flag/package.json
- yarn.lock
There are multiple TS issues because the `@types/react` & `@types/react-dom` versions mismatch. Also, `rollup` dependency is missing from the `feature-flag` pkg. This PR fixes both issues.
Run `yarn build` in the project root.
> fix build leads to empty dist

- .changeset/brave-mugs-crash.md
- package.json
[Lifecycle events don't work in yarn v3](https://github.com/conventional-changelog/standard-version/issues/872). That's why I had to put build to release so that we build the packages before releasing.
Run `yarn release`.
> Put build to release

- .changeset/clever-phones-melt.md
- packages/design-system/package.json
- packages/design-system/src/atoms/tooltip/index.d.ts
- packages/design-system/src/atoms/tooltip/index.web.tsx
- packages/design-system/src/atoms/tooltip/tooltip.stories.tsx
- yarn.lock
- Remove FloatingOverlay so user can interact with background.
- Add supoprt to manual open/close control.
- Tooltip max width set to 250px.
> fix: Better tooltip support

- .changeset/proud-carpets-mix.md
- packages/design-system/src/atoms/anchor/index.tsx
- packages/design-system/src/atoms/tooltip/tooltip.stories.tsx
- packages/design-system/src/atoms/typography/index.tsx
- packages/design-system/src/molecules/accountDropdown/accountDropdown.stories.tsx
- packages/design-system/src/molecules/accountDropdown/index.tsx
- packages/design-system/src/molecules/connectWeb3Button/index.tsx
Made `AccountDropdown` ready for native. If we want a consistent API for the library, we have to get rid of class names & HTML elements (use `native-base` or `react-native` instead). It'll allow our library to accept the unified `style` prop for both `native` & `web`. Moreover, it'll make more components cross-platform out of the box.
1. `yarn start`
2. Go to `Account Dropdwon` story.
> Make AccountDropdown ready for native

- .changeset/nice-baboons-learn.md
- packages/design-system/rollup.config.js
There is a weird bug that `react-native-web-linear-gradient` is included in the `dist`. We don't need any library inside `dist`, so I marked both `peerDependencies` & `dependencies` as `external`.
1. Run `yarn build` inside the design system.
2. Check that `dist/web/esm/node_modules` contains only `tslib`.
> Exclude dependencies from dist

- .changeset/tidy-bags-kneel.md
- packages/design-system/package.json
- packages/design-system/rollup.config.js
- yarn.lock
Fixed RN aliases:
1. Alias to web if the target is the `web`.
2. Use `externals` Rollup plugin so aliases work correctly.
1. Run `yarn build` inside `design-system`.
2. Check that files under `dist/web` don't have `react-native` & `react-native-linear-gradient` imports.
3. Ensure that files under `dist/web` have `react-native-web` & `react-native-web-linear-gradien` imports.
4. Check that files `dist/native` follow the rules above, but in reverse.
> Fix react-native aliases

- .changeset/tiny-actors-cheer.md
- packages/design-system/src/molecules/connectWeb3Options/index.tsx
- packages/design-system/src/styles/container.ts
- packages/design-system/src/styles/theme.ts
Removed classNames from ConnectWeb3Options. Replaced with the common style definitions.
1. Run `yarn start` inside `design-system` package.
> Make ConnectWeb3Options component style-agnostic

- .changeset/proud-masks-act.md
- packages/design-system/.ondevice/storybook.requires.js
- packages/design-system/src/molecules/information/index.tsx
- packages/design-system/src/molecules/information/information.stories.tsx
Added `Information` component.
1. Run storybooks for all the platforms.
2. Check that the rendered result matches the screenshots below.
> Add information component

- .changeset/old-teachers-notice.md
- packages/feature-flag/src/index.tsx
- Used polyfill for `Promise.allSettled` because it's not supported in RN.
> use promise all settled polyfill

- .changeset/dry-items-think.md
- packages/design-system/src/atoms/popover/index.web.tsx
- packages/design-system/src/molecules/information/index.tsx
- packages/design-system/src/molecules/select/index.tsx
- packages/design-system/src/molecules/select/select.stories.tsx
- packages/design-system/src/molecules/select/select.test.tsx
- Fixed Select search functionality.
- Allowed to clear the Select field.
- Fixed `Popover`'s `matchReferenceWidth` property to work correctly.
- Allowed `Information` to accept `null` children.
1. Run storybooks for all the platforms.
2. Check `Select` component to work correctly.
> Fix select search & allow information to accept null children

- .changeset/quick-peaches-notice.md
- packages/api/src/auth/index.ts
- Use post payload instead of query params for `/token` request.
> Use post payload instead of query params

- .changeset/smart-falcons-refuse.md
- packages/api/package.json
- packages/api/src/client/index.test.ts
- packages/api/src/client/index.ts
- packages/api/src/client/types.ts
- yarn.lock
- Refactored client to decrease constructor arguments.
- Extended client from event emitter to react on 401.
- `yarn test`.
> Refactor client & extend from event emitter

- .changeset/shaggy-geese-attack.md
- packages/design-system/ios/Podfile.lock
- packages/design-system/src/hooks/modal.ts
- packages/design-system/src/organisms/modal/modal.stories.tsx
When the modal is open the scroll background will be blocked.
> fix: Prevent scroll when modal is open

- .mailmap
This change adds a `.mailmap` file in the root of the repository, which is used by `git-shortlog` and friends to aggregate contribution information from different commit authors, which is useful when an individual has used multiple names or email addresses in different commits.
```
git shortlog -sne
```
> feat: add mailmap

- .changeset/clever-panthers-judge.md
- packages/api/@types/better-memory-queue/index.d.ts
- packages/api/README.md
- packages/api/src/client/client.test.ts
- packages/api/src/client/client.ts
- packages/api/src/client/types.ts
- packages/api/src/client/utils.ts
- packages/api/tsconfig.json
- Added base API url support by the client.
- Made `getClientVersion` optional.
`yarn test`
> Add base API url support

- .changeset/gold-eggs-kiss.md
- packages/sdk/src/auth/sdk.test.ts
- packages/sdk/src/auth/sdk.ts
- packages/sdk/src/auth/types.ts
- Used `removeItem` instead of `setItem` to clear the storage
`yarn test`
> Use removeItem instead of setItem to undefined in storage

- .changeset/big-dragons-shave.md
- packages/design-system/src/atoms/input/index.tsx
- packages/design-system/src/atoms/input/input.stories.tsx
- packages/design-system/src/atoms/input/input.test.tsx
- packages/design-system/src/molecules/select/index.tsx
- packages/design-system/src/utils/converters.ts
- packages/design-system/src/utils/index.ts
- Added disabled state for `Input`.
- Added `number` type for `Input`.
1. `yarn start`
2. Go to `Input` => `Disabled`.
3. Ensure that the input is not editable.
4. Ensure that the input has gray color.
5. Go to `Input` => `Numeric`.
6. Ensure that it allows only numbers to be entered.
> Add input disabled state

- .changeset/chatty-timers-occur.md
- packages/design-system/rollup.config.js
- Fixed SVG rendering by excluding SVG files from rollup image plugin.
> Fix SVG rendering

- .changeset/small-cups-trade.md
- packages/design-system/src/organisms/uniswapWidget/index.d.ts
- packages/design-system/src/organisms/uniswapWidget/index.native.tsx
- packages/design-system/src/organisms/uniswapWidget/index.web.tsx
- packages/design-system/src/organisms/uniswapWidget/uniswapWidget.stories.tsx
- Removed uniswap widget css import & added a native fallback
> Remove uniswap widget css import & add native fallback

- .changeset/dry-zoos-hang.md
- packages/api-client/src/client.test.ts
- packages/api-client/src/client.ts
- packages/api-client/src/errors.ts
- packages/api-client/src/index.ts
- Added `onDestroy` callback that will reject when refresh tokens is unsuccessful.
> Fix api client never resolves requests because of queue destroy

- .changeset/odd-ways-hope.md
- packages/session-manager/src/native-session-provider.tsx
- packages/session-manager/src/session-provider.test.tsx
- packages/session-manager/src/session-provider.tsx
- Fixed session provider token generation.
- Currently, it passes an object to `generateToken`. Instead, we need to have a plain code string.
`yarn test`
https://www.loom.com/share/122b501891684db99ec814cc4f1af6b3
> Fix session provider token generation

- .changeset/cyan-ravens-wash.md
- .changeset/dull-otters-beg.md
- packages/api-client/src/request-manager.ts
- packages/auth-sdk/src/sdk.ts
- Added cleanup on user fetch failure.
- Allowed to override API Client headers.
- We need when a custom `getUser` function is provided.
> Cleanup on user fetch failure

- .changeset/olive-toes-remain.md
- examples/example-node-api-client/transaction.ts
- examples/example-node-api-client/users.ts
- packages/api/src/user/types.ts
- packages/api/src/user/user.ts
- Formatted the way we pass response to `printTable()` in `getPlatformUserBalance().`
- Added ResponseType and TokenSymbolType, as well as a type guard to the formatted response
- Created ResponseType and TokenSymbolType
- Added type guard to check the type of response.token and conditionally access the 'symbol' property. 
Now when the table is printed, the token column contains the name of the token instead of `Object object`
Run `yarn start` in examples/example-node-api, choose **Get Platform User Balance** option in the CLI and pass the credentials.
> bug: update formatting of the response for Get Platform User balance

- .changeset/itchy-gorillas-dress.md
- packages/design-system/src/organisms/table/table.native.tsx
- packages/design-system/src/organisms/table/table.web.tsx
Fixed Table search is not shown when no filter
> Fixed Table search is not shown when no filter

- .changeset/hip-walls-confess.md
- packages/design-system/src/atoms/typographyV2/index.tsx
- packages/design-system/src/atoms/typographyV2/typographyV2.stories.tsx
- packages/design-system/src/molecules/select/index.tsx
- packages/design-system/src/molecules/selectV2/index.tsx
- Allowed TypographyV2 to render nested texts.
- Fixed an issue with cursor: pointer style being passed to native components.
> Allow TypographyV2 to render nested texts

- .changeset/tall-queens-share.md
- .changeset/tough-yaks-draw.md
- packages/design-system/src/molecules/accountDropdown/index.tsx
- packages/design-system/src/molecules/accountDropdownWagmi/index.tsx
- packages/design-system/src/molecules/tokenCard/index.tsx
- packages/design-system/src/molecules/tokenCard/tokenCard.test.tsx
- packages/web3/src/utils/utils.ts
- Changed Etherscan to Explorer.
- Added Form to ETHERSCAN_DATA.
> feat: change etherscan to explorer
